name: Feature request
description: Navrhnout novou funkci nebo vylepšení
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Jaký problém nebo use-case řešíte?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Navrhované řešení
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Zvažované alternativy
  - type: textarea
    id: context
    attributes:
      label: Dodatečný kontext (odkazy, screenshoty)
